# ================================================================================
# llm_prompt_ollama パッケージの公開 API を再エクスポートする
# ================================================================================
from .ollama_client import OllamaClient, OllamaError
from .download import (
    HF_GGUF_FILENAME,
    HF_REPO_ID,
    SETTING_MODELS_DIR,
    default_gguf_path,
    default_models_dir,
    describe_gguf_status,
    download_default_gguf,
    download_gguf,
    get_models_dir,
    gguf_path_for,
)
from .model_setup import (
    DEFAULT_GGUF_FILENAME,
    DEFAULT_MODEL_NAME,
    DEFAULT_OLLAMA_URL,
    SETTING_API_URL,
    SETTING_DEFAULT_GGUF,
    SETTING_DEFAULT_MODEL,
    SETTING_OLLAMA_BIN,
    build_modelfile,
    connection_help,
    create_model,
    extension_root,
    find_ollama_bin,
    get_setting,
    start_ollama_serve,
)
from .models_catalog import (
    choices_for_ui,
    default_model,
    default_model_id,
    get_model,
    has_catalog_models,
    list_models,
    load_models_catalog,
    require_model,
)
from .presets import (
    DEFAULT_LANG,
    DEFAULT_PRESET,
    LANG_CHOICES,
    PRESET_CHOICES,
    instruction_for_preset,
    is_nsfw_preset,
)

__all__ = [
    "OllamaClient",
    "OllamaError",
    "HF_GGUF_FILENAME",
    "HF_REPO_ID",
    "SETTING_MODELS_DIR",
    "default_gguf_path",
    "default_models_dir",
    "describe_gguf_status",
    "download_default_gguf",
    "download_gguf",
    "get_models_dir",
    "gguf_path_for",
    "DEFAULT_GGUF_FILENAME",
    "DEFAULT_MODEL_NAME",
    "DEFAULT_OLLAMA_URL",
    "SETTING_API_URL",
    "SETTING_DEFAULT_GGUF",
    "SETTING_DEFAULT_MODEL",
    "SETTING_OLLAMA_BIN",
    "build_modelfile",
    "connection_help",
    "create_model",
    "extension_root",
    "find_ollama_bin",
    "get_setting",
    "start_ollama_serve",
    "choices_for_ui",
    "default_model",
    "default_model_id",
    "get_model",
    "has_catalog_models",
    "list_models",
    "load_models_catalog",
    "require_model",
    "DEFAULT_LANG",
    "DEFAULT_PRESET",
    "LANG_CHOICES",
    "PRESET_CHOICES",
    "instruction_for_preset",
    "is_nsfw_preset",
]
